name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
        matrix:
            ghc: ['8.8.3', '8.10.3']
            cabal: ['3.0.0.0', '3.2.0.0']
            os: [ubuntu-latest]

            include:
                -
                    ghc: 8.10.3
                    cabal: 3.2.0.0
                    os: macOS-latest
                -
                    ghc: 8.10.3
                    cabal: 3.2.0.0
                    os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks all
    - name: Build
      run: cabal build --flag develop --enable-tests --enable-benchmarks all
    - name: Run tests
      run: |
        cabal test all
        cabal sdist all
